/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.LocalVariable#getLocal_expression <em>Local expression</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLocalVariable()
 * @model
 * @generated
 */
public interface LocalVariable extends Variable
{
  /**
   * Returns the value of the '<em><b>Local expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local expression</em>' containment reference.
   * @see #setLocal_expression(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLocalVariable_Local_expression()
   * @model containment="true"
   * @generated
   */
  Expression getLocal_expression();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.LocalVariable#getLocal_expression <em>Local expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local expression</em>' containment reference.
   * @see #getLocal_expression()
   * @generated
   */
  void setLocal_expression(Expression value);

} // LocalVariable
