/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parenthesis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Parenthesis#getParenthesizedExpression <em>Parenthesized Expression</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getParenthesis()
 * @model
 * @generated
 */
public interface Parenthesis extends Expression
{
  /**
   * Returns the value of the '<em><b>Parenthesized Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parenthesized Expression</em>' containment reference.
   * @see #setParenthesizedExpression(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getParenthesis_ParenthesizedExpression()
   * @model containment="true"
   * @generated
   */
  Expression getParenthesizedExpression();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Parenthesis#getParenthesizedExpression <em>Parenthesized Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parenthesized Expression</em>' containment reference.
   * @see #getParenthesizedExpression()
   * @generated
   */
  void setParenthesizedExpression(Expression value);

} // Parenthesis
