/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.EcoreUtil2
import dk.sdu.mmmi.mdsd.math.GlobalVariable
import dk.sdu.mmmi.mdsd.math.Model
import dk.sdu.mmmi.mdsd.math.MathPackage.Literals

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	

	@Check
	def noRepeatedGlobalVariablwes(GlobalVariable globalVariable) {
		val model = EcoreUtil2.getRootContainer(globalVariable) as Model;
		val globalVariables = model.variables;
		var occurences = 0;
		for (gv : globalVariables) {
			if(gv.name == globalVariable.name){
				occurences++;
			}
		}
		if(occurences > 1){
			error("Multiple global variables cannot share the same name.", globalVariable, Literals.VARIABLE__NAME)
		}
	}
	
}
