/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math.impl;

import dk.sdu.mmmi.mdsd.math.Expression;
import dk.sdu.mmmi.mdsd.math.MathPackage;
import dk.sdu.mmmi.mdsd.math.Parenthesis;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parenthesis</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.impl.ParenthesisImpl#getParenthesizedExpression <em>Parenthesized Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParenthesisImpl extends ExpressionImpl implements Parenthesis
{
  /**
   * The cached value of the '{@link #getParenthesizedExpression() <em>Parenthesized Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParenthesizedExpression()
   * @generated
   * @ordered
   */
  protected Expression parenthesizedExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParenthesisImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathPackage.Literals.PARENTHESIS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getParenthesizedExpression()
  {
    return parenthesizedExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParenthesizedExpression(Expression newParenthesizedExpression, NotificationChain msgs)
  {
    Expression oldParenthesizedExpression = parenthesizedExpression;
    parenthesizedExpression = newParenthesizedExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION, oldParenthesizedExpression, newParenthesizedExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParenthesizedExpression(Expression newParenthesizedExpression)
  {
    if (newParenthesizedExpression != parenthesizedExpression)
    {
      NotificationChain msgs = null;
      if (parenthesizedExpression != null)
        msgs = ((InternalEObject)parenthesizedExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION, null, msgs);
      if (newParenthesizedExpression != null)
        msgs = ((InternalEObject)newParenthesizedExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION, null, msgs);
      msgs = basicSetParenthesizedExpression(newParenthesizedExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION, newParenthesizedExpression, newParenthesizedExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION:
        return basicSetParenthesizedExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION:
        return getParenthesizedExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION:
        setParenthesizedExpression((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION:
        setParenthesizedExpression((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MathPackage.PARENTHESIS__PARENTHESIZED_EXPRESSION:
        return parenthesizedExpression != null;
    }
    return super.eIsSet(featureID);
  }

} //ParenthesisImpl
