/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.mmmi.mdsd.ide.contentassist.antlr.internal.InternalMathParser;
import dk.sdu.mmmi.mdsd.services.MathGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MathParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MathGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MathGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAdditionAndSubtractionExpressionAccess().getAlternatives_1_0(), "rule__AdditionAndSubtractionExpression__Alternatives_1_0");
			builder.put(grammarAccess.getMultiplicationAndDivisionExpressionAccess().getAlternatives_1_0(), "rule__MultiplicationAndDivisionExpression__Alternatives_1_0");
			builder.put(grammarAccess.getValueExpressionAccess().getAlternatives(), "rule__ValueExpression__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getGlobalVariableAccess().getGroup(), "rule__GlobalVariable__Group__0");
			builder.put(grammarAccess.getLocalVariableAccess().getGroup(), "rule__LocalVariable__Group__0");
			builder.put(grammarAccess.getAdditionAndSubtractionExpressionAccess().getGroup(), "rule__AdditionAndSubtractionExpression__Group__0");
			builder.put(grammarAccess.getAdditionAndSubtractionExpressionAccess().getGroup_1(), "rule__AdditionAndSubtractionExpression__Group_1__0");
			builder.put(grammarAccess.getAdditionAndSubtractionExpressionAccess().getGroup_1_0_0(), "rule__AdditionAndSubtractionExpression__Group_1_0_0__0");
			builder.put(grammarAccess.getAdditionAndSubtractionExpressionAccess().getGroup_1_0_1(), "rule__AdditionAndSubtractionExpression__Group_1_0_1__0");
			builder.put(grammarAccess.getMultiplicationAndDivisionExpressionAccess().getGroup(), "rule__MultiplicationAndDivisionExpression__Group__0");
			builder.put(grammarAccess.getMultiplicationAndDivisionExpressionAccess().getGroup_1(), "rule__MultiplicationAndDivisionExpression__Group_1__0");
			builder.put(grammarAccess.getMultiplicationAndDivisionExpressionAccess().getGroup_1_0_0(), "rule__MultiplicationAndDivisionExpression__Group_1_0_0__0");
			builder.put(grammarAccess.getMultiplicationAndDivisionExpressionAccess().getGroup_1_0_1(), "rule__MultiplicationAndDivisionExpression__Group_1_0_1__0");
			builder.put(grammarAccess.getValueExpressionAccess().getGroup_0(), "rule__ValueExpression__Group_0__0");
			builder.put(grammarAccess.getValueExpressionAccess().getGroup_1(), "rule__ValueExpression__Group_1__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
			builder.put(grammarAccess.getModelAccess().getVariablesAssignment_2(), "rule__Model__VariablesAssignment_2");
			builder.put(grammarAccess.getGlobalVariableAccess().getNameAssignment_2(), "rule__GlobalVariable__NameAssignment_2");
			builder.put(grammarAccess.getGlobalVariableAccess().getExpressionAssignment_4(), "rule__GlobalVariable__ExpressionAssignment_4");
			builder.put(grammarAccess.getLocalVariableAccess().getNameAssignment_2(), "rule__LocalVariable__NameAssignment_2");
			builder.put(grammarAccess.getLocalVariableAccess().getLocal_expressionAssignment_4(), "rule__LocalVariable__Local_expressionAssignment_4");
			builder.put(grammarAccess.getLocalVariableAccess().getExpressionAssignment_6(), "rule__LocalVariable__ExpressionAssignment_6");
			builder.put(grammarAccess.getAdditionAndSubtractionExpressionAccess().getRightAssignment_1_1(), "rule__AdditionAndSubtractionExpression__RightAssignment_1_1");
			builder.put(grammarAccess.getMultiplicationAndDivisionExpressionAccess().getRightAssignment_1_1(), "rule__MultiplicationAndDivisionExpression__RightAssignment_1_1");
			builder.put(grammarAccess.getValueExpressionAccess().getParenthesizedExpressionAssignment_0_2(), "rule__ValueExpression__ParenthesizedExpressionAssignment_0_2");
			builder.put(grammarAccess.getValueExpressionAccess().getValueAssignment_1_1(), "rule__ValueExpression__ValueAssignment_1_1");
			builder.put(grammarAccess.getVariableReferenceAccess().getVariableAssignment(), "rule__VariableReference__VariableAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MathGrammarAccess grammarAccess;

	@Override
	protected InternalMathParser createParser() {
		InternalMathParser result = new InternalMathParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MathGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
